// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwcdrhzmsrlrlzlzbesg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3Y2RyaHptc3Jscmx6bHpiZXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDk3MDQsImV4cCI6MjA2MjM4NTcwNH0.U7vQh4wPxODfEosT7aKvNv85ZmAsOJrZNaSaL3O7x5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);